repos:
  - repo: https://github.com/hukkin/mdformat
    rev: "1.0.0"
    hooks:
      - id: mdformat
        name: format Markdown
        types: [markdown]
        exclude: ^\.github/
        additional_dependencies:
          - mdformat-gfm
          - mdformat-mkdocs[recommended]==5.1.4
        priority: 6
