"""Validate and generate Django HTMX snippets and their documentation."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from htmx_tools.models import (
    CATEGORIES,
    CLASSIFICATIONS,
    SnippetEntry,
    snippet_preview,
    validate_source,
)

ROOT = Path(__file__).resolve().parent.parent
SOURCE_FILE = ROOT / "snippets" / "django-htmx.source.json"
SNIPPET_FILE = ROOT / "snippets" / "django-htmx.json"
DOCS_FILE = ROOT / "docs" / "reference" / "snippets.md"

__all__ = [
    "CATEGORIES",
    "CLASSIFICATIONS",
    "DOCS_FILE",
    "SNIPPET_FILE",
    "SOURCE_FILE",
    "generated_outputs",
    "load_catalog",
    "render_docs",
    "render_snippets",
    "snippet_preview",
    "sync_outputs",
    "validate_catalog",
]


def load_catalog(path: Path = SOURCE_FILE) -> list[dict[str, Any]]:
    """Load a catalog and require an array of object entries."""
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("catalog root must be an array")
    if not all(isinstance(entry, dict) for entry in data):
        raise ValueError("every catalog entry must be an object")
    return data


def _describe_error(exc: ValidationError, label: str) -> str:
    errors = exc.errors()
    missing = sorted(str(err["loc"][-1]) for err in errors if err["type"] == "missing")
    extra = sorted(str(err["loc"][-1]) for err in errors if err["type"] == "extra_forbidden")
    other = [err["msg"] for err in errors if err["type"] not in {"missing", "extra_forbidden"}]

    details = []
    if missing:
        details.append(f"missing {', '.join(missing)}")
    if extra:
        details.append(f"unexpected {', '.join(extra)}")
    if details:
        return f"{label}: invalid fields ({'; '.join(details)})"
    if other:
        return f"{label}: {other[0]}"
    return f"{label}: {exc}"


def validate_catalog(catalog: list[dict[str, Any]]) -> None:
    """Reject malformed, unsafe, duplicate, or unstably ordered entries."""
    if not catalog:
        raise ValueError("catalog must contain at least one entry")

    entries: list[SnippetEntry] = []
    for index, raw in enumerate(catalog, start=1):
        label = raw.get("prefix") or raw.get("name") or f"entry {index}"
        try:
            entries.append(SnippetEntry.model_validate(raw))
        except ValidationError as exc:
            raise ValueError(_describe_error(exc, label)) from exc

    validate_source(entries)


def render_snippets(catalog: list[dict[str, Any]]) -> str:
    """Render the VS Code snippet contribution without documentation metadata."""
    snippets = {
        entry["name"]: {
            "prefix": entry["prefix"],
            "description": entry["description"],
            "body": entry["body"],
        }
        for entry in catalog
    }
    return json.dumps(snippets, ensure_ascii=False, indent=2) + "\n"


def render_docs(catalog: list[dict[str, Any]]) -> str:
    """Render the browsable snippet and example reference."""
    lines = [
        "<!-- Generated by `htmx-tools build-snippets`; edit snippets/django-htmx.source.json. -->",
        "",
        "# Snippets and Examples",
        "",
        "The extension contributes secure Django-first HTMX patterns for `django-html` documents.",
        "Type a prefix to insert the snippet, then move through its editable placeholders.",
        "",
        "Mutating forms include Django's CSRF token. The examples use HTMX syntax shared by",
        "the supported HTMX 2 and HTMX 4 catalogs.",
        "See [Core Django response contracts](../how-to/django-response-contracts.md) for",
        "matching view and response examples.",
        "",
        "## Prefixes",
        "",
        "| Prefix | Classification | Description |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        f"| `{entry['prefix']}` | {CLASSIFICATIONS[entry['classification']]} | "
        f"{entry['description']} |"
        for entry in catalog
    )

    for category in CATEGORIES:
        lines.extend(("", f"## {category}"))
        for entry in catalog:
            if entry["category"] != category:
                continue
            lines.extend(
                (
                    "",
                    f"### `{entry['prefix']}`",
                    "",
                    entry["description"] + ".",
                    "",
                    f"**Classification:** {CLASSIFICATIONS[entry['classification']]}",
                    "",
                    "```django",
                    snippet_preview(entry["body"]),
                    "```",
                    "",
                    f"**Endpoint or context:** {entry['usage']}",
                )
            )

    return "\n".join(lines) + "\n"


def generated_outputs(
    source_path: Path = SOURCE_FILE,
    snippet_path: Path = SNIPPET_FILE,
    docs_path: Path = DOCS_FILE,
) -> dict[Path, str]:
    """Load and validate the source before rendering either output."""
    catalog = load_catalog(source_path)
    validate_catalog(catalog)
    return {
        snippet_path: render_snippets(catalog),
        docs_path: render_docs(catalog),
    }


def sync_outputs(outputs: dict[Path, str], *, check: bool) -> list[Path]:
    """Write changed outputs, or return stale paths without writing in check mode."""
    stale = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if not check:
        for path in stale:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(outputs[path], encoding="utf-8")
    return stale
